Repository vsla/BugHunter, pull requests merged in 2019-09, with the labels that each got.

#6 Feature/users stories
  docs/iteracao_0/userHistories.md
  docs/iteracao_0/userStories.md
Labels: documentation

#7 Primeiro modelo relacional
  docs/img/modelo_relacional0.png
Labels: documentation

#10 Adicionando PostMortem da Iteracao 0
  docs/iteracao_0/postmortem_0.md
Labels: documentation

#11 Atualização da tela da iteração 0
  docs/iteracao_0/iteracao_0.md
Labels: documentation

#13 Adde metting doc da iteracao 0
  docs/Meetings.md
Labels: documentation

#22 Levantar servidor
  app/Backend/bughunter/.gitignore
  app/Backend/bughunter/.ruby-version
  app/Backend/bughunter/Gemfile
  app/Backend/bughunter/Gemfile.lock
  app/Backend/bughunter/README.md
  app/Backend/bughunter/Rakefile
  app/Backend/bughunter/app/channels/application_cable/channel.rb
  app/Backend/bughunter/app/channels/application_cable/connection.rb
  app/Backend/bughunter/app/controllers/application_controller.rb
  app/Backend/bughunter/app/controllers/concerns/.keep
  app/Backend/bughunter/app/jobs/application_job.rb
  app/Backend/bughunter/app/mailers/application_mailer.rb
  app/Backend/bughunter/app/models/application_record.rb
  app/Backend/bughunter/app/models/concerns/.keep
  app/Backend/bughunter/app/views/layouts/mailer.html.erb
  app/Backend/bughunter/app/views/layouts/mailer.text.erb
  app/Backend/bughunter/bin/bundle
  app/Backend/bughunter/bin/rails
  app/Backend/bughunter/bin/rake
  app/Backend/bughunter/bin/setup
  app/Backend/bughunter/bin/spring
  app/Backend/bughunter/bin/update
  app/Backend/bughunter/config.ru
  app/Backend/bughunter/config/application.rb
  app/Backend/bughunter/config/boot.rb
  app/Backend/bughunter/config/cable.yml
  app/Backend/bughunter/config/credentials.yml.enc
  app/Backend/bughunter/config/database.yml
  app/Backend/bughunter/config/environment.rb
  app/Backend/bughunter/config/environments/development.rb
  app/Backend/bughunter/config/environments/production.rb
  app/Backend/bughunter/config/environments/test.rb
  app/Backend/bughunter/config/initializers/application_controller_renderer.rb
  app/Backend/bughunter/config/initializers/backtrace_silencers.rb
  app/Backend/bughunter/config/initializers/cors.rb
  app/Backend/bughunter/config/initializers/filter_parameter_logging.rb
  app/Backend/bughunter/config/initializers/inflections.rb
  app/Backend/bughunter/config/initializers/mime_types.rb
  app/Backend/bughunter/config/initializers/wrap_parameters.rb
  app/Backend/bughunter/config/locales/en.yml
  app/Backend/bughunter/config/puma.rb
  app/Backend/bughunter/config/routes.rb
  app/Backend/bughunter/config/spring.rb
  app/Backend/bughunter/config/storage.yml
  app/Backend/bughunter/db/seeds.rb
  app/Backend/bughunter/lib/tasks/.keep
  app/Backend/bughunter/log/.keep
  app/Backend/bughunter/public/robots.txt
  app/Backend/bughunter/storage/.keep
  app/Backend/bughunter/test/controllers/.keep
  app/Backend/bughunter/test/fixtures/.keep
  app/Backend/bughunter/test/fixtures/files/.keep
  app/Backend/bughunter/test/integration/.keep
  app/Backend/bughunter/test/mailers/.keep
  app/Backend/bughunter/test/models/.keep
  app/Backend/bughunter/test/test_helper.rb
  app/Backend/bughunter/tmp/.keep
  app/Backend/bughunter/vendor/.keep
Labels: feature

#23 Atualização gem e adição rspec
  app/Backend/bughunter/.rspec
  app/Backend/bughunter/Gemfile
  app/Backend/bughunter/Gemfile.lock
  app/Backend/bughunter/spec/rails_helper.rb
  app/Backend/bughunter/spec/spec_helper.rb
Labels: feature

#17 Reuniões interação 1 --> semana1/semana2
  docs/Meetings.md
Labels: documentation

#28 Reunião do dia 21/09/2019
  docs/Meetings.md
Labels: planning

#35 Feature/spt1.4/form projeto empresa
  app/frontend/package-lock.json
  app/frontend/package.json
  app/frontend/src/app/components/MessageBar.jsx
  app/frontend/src/app/pages/Company/pages/Projects/FormProject/FormProject.jsx
  app/frontend/src/app/pages/Company/pages/Projects/FormProject/components/Form.jsx
  app/frontend/src/app/pages/Company/pages/Projects/ProjectsList/Projects.jsx
  app/frontend/src/app/pages/Company/pages/Projects/ProjectsList/components/ProjectsList.jsx
  app/frontend/src/app/pages/Company/pages/Projects/ProjectsList/components/StatusCards.jsx
  app/frontend/src/app/routes/Routes.jsx
Labels: feature
